// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT8auzhKnzehXLsxGh16JAsZkIwFoiuto',
    appId: '1:66798181914:web:919145c2e61d2ea4613ba3',
    messagingSenderId: '66798181914',
    projectId: 'basic-flutter-project',
    authDomain: 'basic-flutter-project.firebaseapp.com',
    storageBucket: 'basic-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh6u3EAeMuoOwX5BDTuyPvHsom6K2yOkk',
    appId: '1:66798181914:android:1c2071bd86a04be2613ba3',
    messagingSenderId: '66798181914',
    projectId: 'basic-flutter-project',
    storageBucket: 'basic-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkbrA4qPcS7T9EuLTrrUM2YcYZZ0jy5dE',
    appId: '1:66798181914:ios:5509efdba3f0d473613ba3',
    messagingSenderId: '66798181914',
    projectId: 'basic-flutter-project',
    storageBucket: 'basic-flutter-project.appspot.com',
    iosBundleId: 'com.hello.basicFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkbrA4qPcS7T9EuLTrrUM2YcYZZ0jy5dE',
    appId: '1:66798181914:ios:0ab7ac4d63efd932613ba3',
    messagingSenderId: '66798181914',
    projectId: 'basic-flutter-project',
    storageBucket: 'basic-flutter-project.appspot.com',
    iosBundleId: 'com.hello.basicFlutter.RunnerTests',
  );
}
